// Copyright (c) the go-tex authors.
// SPDX-License-Identifier: BSD-3-Clause

package playground

import (
	"strings"

	"github.com/go-widgets/toolkit"
)

// The render pane blits rasterised page bitmaps to the canvas, which is what
// makes paging, zoom and the click↔source-line linking work. A bitmap, though,
// is not text: the preview could not be searched, could not be read by a screen
// reader, and exposed nothing to the page around it.
//
// Since go-tex/engine v0.168.0 every SVG page also carries its characters in an
// invisible <text> layer. This file lifts that layer out of the page — keeping
// the <svg>, the <g> transforms and nothing else — so the host can lay it over
// the rasterised card as real DOM. The pixels on the canvas do not change; what
// changes is that the browser now knows what they say.
//
// The overlay is inert to the pointer (see the host's CSS): a click still
// reaches the canvas and still moves the caret to the matching source line.
// Find, the accessibility tree and a programmatic selection read the text; a
// drag does not select it. That is the deliberate trade — the linking is an
// existing feature and this must not take it away.

// TextOverlay is one page's searchable text, ready to place. The host reads it
// from [State.TextOverlays] and turns it into DOM.
type TextOverlay struct {
	// Page is 1-based, matching PagedView.
	Page int
	// SVG holds only the invisible <text> runs, in the page's own viewBox.
	SVG string
	// Rect is where the card is drawn and Clip the part the pane still shows,
	// both in the surface's DEVICE pixels — a host laying out in CSS pixels
	// divides by the device pixel ratio.
	Rect, Clip toolkit.Rect
}

// textOverlaySVG returns page, stripped of every drawing element, keeping only
// the structure the text sits in. The result shares the page's viewBox, so
// stretching it over the rasterised card lands each run on its own glyphs at any
// zoom.
//
// It scans the engine's own output rather than parsing XML in general: that
// output is generated by [engine.RenderPage], has no comments, no CDATA and no
// processing instructions, and every element is either self-closing or paired.
// An input that does not look like that yields "" rather than a broken overlay.
func textOverlaySVG(page string) string {
	if !strings.HasPrefix(page, "<svg") {
		return ""
	}
	var out strings.Builder
	kept := false
	for i := 0; i < len(page); {
		lt := strings.IndexByte(page[i:], '<')
		if lt < 0 {
			break
		}
		i += lt
		gt := strings.IndexByte(page[i:], '>')
		if gt < 0 {
			return "" // an unterminated tag: not the output this understands
		}
		tag := page[i : i+gt+1]
		name := elementName(tag)
		switch name {
		case "text":
			// Copied whole, tspans and character data included.
			end := strings.Index(page[i:], "</text>")
			if end < 0 {
				return ""
			}
			out.WriteString(page[i : i+end+len("</text>")])
			kept = true
			i += end + len("</text>")
			continue
		case "svg":
			// The root, re-fitted: the pt width/height are replaced by the card
			// size the host gives it, and the viewBox is stretched to fill it
			// exactly so no rounding can letterbox the runs off their glyphs.
			out.WriteString(refitRoot(tag))
		case "/svg", "g", "/g", "a", "/a":
			// Structure: the transforms the text is positioned by.
			out.WriteString(tag)
		default:
			// A drawing element (path, rect, image, …): the canvas already has it.
		}
		i += gt + 1
	}
	if !kept {
		return "" // a page with no text is not worth an overlay element
	}
	return out.String()
}

// elementName is the tag's element name, prefixed with "/" for a closing tag.
// A self-closing tag reports its own name, so <path .../> reads as "path".
func elementName(tag string) string {
	s := strings.TrimSuffix(strings.TrimPrefix(tag, "<"), ">")
	s = strings.TrimSuffix(s, "/")
	if s == "" {
		return ""
	}
	closing := strings.HasPrefix(s, "/")
	s = strings.TrimPrefix(s, "/")
	if cut := strings.IndexAny(s, " \t\n"); cut >= 0 {
		s = s[:cut]
	}
	if closing {
		return "/" + s
	}
	return s
}

// TextOverlays returns the searchable text of every page currently ON SCREEN in
// the render pane, with where to put it. The host creates one element per entry
// and removes the rest.
//
// It is empty whenever nothing should be shown: the Log tab is in front, the
// pane has no room, or the compile produced no text. Reading it every frame is
// what keeps the overlay glued to the card through a scroll, a zoom, a page flip
// or a pane resize — the placement comes from [toolkit.PagedView.PageRect], the
// same layout Draw blits from, so the two cannot drift.
func (s *State) TextOverlays() []TextOverlay {
	if s.rightPane == nil || s.rightPane.activeTab() != tabRender {
		return nil
	}
	var out []TextOverlay
	for i, svg := range s.textLayers {
		if svg == "" {
			continue
		}
		rect, clip, ok := s.renderView.PageRect(i + 1)
		if !ok || clip.W <= 0 || clip.H <= 0 {
			continue // no such page, or none of it is on screen
		}
		out = append(out, TextOverlay{Page: i + 1, SVG: svg, Rect: rect, Clip: clip})
	}
	return out
}

// refitRoot strips the root <svg>'s absolute width and height — they are in
// points, and the overlay is sized in CSS pixels by whatever the render pane
// currently shows — and pins the viewBox to fill that box exactly. Without
// preserveAspectRatio="none" the browser letterboxes on any rounding difference,
// which slides every run a pixel or two off its glyphs.
func refitRoot(tag string) string {
	tag = dropAttr(tag, "width")
	tag = dropAttr(tag, "height")
	return strings.TrimSuffix(tag, ">") + ` preserveAspectRatio="none">`
}

// dropAttr removes a name="value" attribute from a start tag. Only the engine's
// own output is fed to it, where every attribute value is double-quoted and
// contains no quote of its own.
func dropAttr(tag, name string) string {
	at := strings.Index(tag, " "+name+`="`)
	if at < 0 {
		return tag
	}
	rest := tag[at+len(name)+3:]
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return tag
	}
	return tag[:at] + rest[end+1:]
}
